package com.example.viridis.dummyData

import com.example.viridis.data.model.Plant

val dummyPlants = listOf(
    Plant(
        id = "1",
        name = "Aloe Vera",
        scientificName = "Aloe barbadensis",
        watering = "Bi-weekly",
        recommendations = listOf("Keep in indirect sunlight.", "Water regularly but avoid overwatering.", "Use well-draining soil."),
        imageUrl = "https://source.unsplash.com/featured/?plant,0",
        streak = 3,
        lastWatered = "2025-05-08",
        idGarden = 1,
        difficulty = "Medium",
        shadeLevel = 3
    ),
    Plant(
        id = "2",
        name = "Snake Plant",
        scientificName = "Sansevieria trifasciata",
        watering = "Bi-weekly",
        recommendations = listOf("Keep in indirect sunlight.", "Water regularly but avoid overwatering.", "Fertilize monthly during growing season."),
        imageUrl = "https://source.unsplash.com/featured/?plant,1",
        streak = 16,
        lastWatered = "2025-05-24",
        idGarden = 1,
        difficulty = "Hard",
        shadeLevel = 5
    ),
    Plant(
        id = "3",
        name = "Peace Lily",
        scientificName = "Spathiphyllum wallisii",
        watering = "Daily",
        recommendations = listOf("Mist leaves occasionally.", "Keep in indirect sunlight.", "Use well-draining soil."),
        imageUrl = "https://source.unsplash.com/featured/?plant,2",
        streak = 15,
        lastWatered = "2025-05-02",
        idGarden = 1,
        difficulty = "Medium",
        shadeLevel = 4
    ),
    Plant(
        id = "4",
        name = "Spider Plant",
        scientificName = "Chlorophytum comosum",
        watering = "Weekly",
        recommendations = listOf("Keep away from pets.", "Mist leaves occasionally.", "Use well-draining soil."),
        imageUrl = "https://source.unsplash.com/featured/?plant,3",
        streak = 15,
        lastWatered = "2025-05-06",
        idGarden = 1,
        difficulty = "Medium",
        shadeLevel = 3
    ),
    Plant(
        id = "5",
        name = "Pothos",
        scientificName = "Epipremnum aureum",
        watering = "Daily",
        recommendations = listOf("Mist leaves occasionally.", "Fertilize monthly during growing season.", "Keep in indirect sunlight."),
        imageUrl = "https://source.unsplash.com/featured/?plant,4",
        streak = 11,
        lastWatered = "2025-05-22",
        idGarden = 2,
        difficulty = "Hard",
        shadeLevel = 5
    ),
    Plant(
        id = "6",
        name = "ZZ Plant",
        scientificName = "Zamioculcas zamiifolia",
        watering = "Every 3 days",
        recommendations = listOf("Keep away from pets.", "Use well-draining soil.", "Mist leaves occasionally."),
        imageUrl = "https://source.unsplash.com/featured/?plant,5",
        streak = 16,
        lastWatered = "2025-05-11",
        idGarden = 2,
        difficulty = "Hard",
        shadeLevel = 1
    ),
    Plant(
        id = "7",
        name = "Fiddle Leaf Fig",
        scientificName = "Ficus lyrata",
        watering = "Every 3 days",
        recommendations = listOf("Keep in indirect sunlight.", "Mist leaves occasionally.", "Keep away from pets."),
        imageUrl = "https://source.unsplash.com/featured/?plant,6",
        streak = 8,
        lastWatered = "2025-05-22",
        idGarden = 2,
        difficulty = "Easy",
        shadeLevel = 3
    ),
    Plant(
        id = "8",
        name = "Rubber Plant",
        scientificName = "Ficus elastica",
        watering = "Bi-weekly",
        recommendations = listOf("Keep away from pets.", "Keep away from pets.", "Use well-draining soil."),
        imageUrl = "https://source.unsplash.com/featured/?plant,7",
        streak = 2,
        lastWatered = "2025-05-16",
        idGarden = 2,
        difficulty = "Hard",
        shadeLevel = 1
    ),
    Plant(
        id = "9",
        name = "Areca Palm",
        scientificName = "Dypsis lutescens",
        watering = "Weekly",
        recommendations = listOf("Fertilize monthly during growing season.", "Water regularly but avoid overwatering.", "Mist leaves occasionally."),
        imageUrl = "https://source.unsplash.com/featured/?plant,8",
        streak = 5,
        lastWatered = "2025-05-17",
        idGarden = 2,
        difficulty = "Easy",
        shadeLevel = 4
    ),
    Plant(
        id = "10",
        name = "Jade Plant",
        scientificName = "Crassula ovata",
        watering = "Bi-weekly",
        recommendations = listOf("Fertilize monthly during growing season.", "Fertilize monthly during growing season.", "Mist leaves occasionally."),
        imageUrl = "https://source.unsplash.com/featured/?plant,9",
        streak = 14,
        lastWatered = "2025-05-13",
        idGarden = 4,
        difficulty = "Easy",
        shadeLevel = 3
    ),
    Plant(
        id = "11",
        name = "Fern",
        scientificName = "Nephrolepis exaltata",
        watering = "Every 3 days",
        recommendations = listOf("Mist leaves occasionally.", "Water regularly but avoid overwatering.", "Keep in indirect sunlight."),
        imageUrl = "https://source.unsplash.com/featured/?plant,10",
        streak = 13,
        lastWatered = "2025-05-21",
        idGarden = 4,
        difficulty = "Easy",
        shadeLevel = 1
    ),
    Plant(
        id = "12",
        name = "Croton",
        scientificName = "Codiaeum variegatum",
        watering = "Weekly",
        recommendations = listOf("Keep in indirect sunlight.", "Mist leaves occasionally.", "Keep away from pets."),
        imageUrl = "https://source.unsplash.com/featured/?plant,11",
        streak = 3,
        lastWatered = "2025-05-10",
        idGarden = 1,
        difficulty = "Medium",
        shadeLevel = 1
    ),
    Plant(
        id = "13",
        name = "Calathea",
        scientificName = "Calathea orbifolia",
        watering = "Every 3 days",
        recommendations = listOf("Keep in indirect sunlight.", "Keep in indirect sunlight.", "Mist leaves occasionally."),
        imageUrl = "https://source.unsplash.com/featured/?plant,12",
        streak = 29,
        lastWatered = "2025-05-03",
        idGarden = 4,
        difficulty = "Easy",
        shadeLevel = 1
    ),
    Plant(
        id = "14",
        name = "Dieffenbachia",
        scientificName = "Dieffenbachia seguine",
        watering = "Weekly",
        recommendations = listOf("Fertilize monthly during growing season.", "Keep in indirect sunlight.", "Keep away from pets."),
        imageUrl = "https://source.unsplash.com/featured/?plant,13",
        streak = 1,
        lastWatered = "2025-05-14",
        idGarden = 2,
        difficulty = "Medium",
        shadeLevel = 1
    ),
    Plant(
        id = "15",
        name = "Bird of Paradise",
        scientificName = "Strelitzia reginae",
        watering = "Weekly",
        recommendations = listOf("Mist leaves occasionally.", "Keep in indirect sunlight.", "Fertilize monthly during growing season."),
        imageUrl = "https://source.unsplash.com/featured/?plant,14",
        streak = 29,
        lastWatered = "2025-05-14",
        idGarden = 4,
        difficulty = "Hard",
        shadeLevel = 3
    ),
    Plant(
        id = "16",
        name = "Dracaena",
        scientificName = "Dracaena marginata",
        watering = "Daily",
        recommendations = listOf("Keep away from pets.", "Use well-draining soil.", "Water regularly but avoid overwatering."),
        imageUrl = "https://source.unsplash.com/featured/?plant,15",
        streak = 16,
        lastWatered = "2025-05-25",
        idGarden = 4,
        difficulty = "Hard",
        shadeLevel = 4
    ),
    Plant(
        id = "17",
        name = "Bamboo Palm",
        scientificName = "Chamaedorea seifrizii",
        watering = "Daily",
        recommendations = listOf("Fertilize monthly during growing season.", "Keep in indirect sunlight.", "Water regularly but avoid overwatering."),
        imageUrl = "https://source.unsplash.com/featured/?plant,16",
        streak = 1,
        lastWatered = "2025-05-01",
        idGarden = 2,
        difficulty = "Medium",
        shadeLevel = 1
    ),
    Plant(
        id = "18",
        name = "Philodendron",
        scientificName = "Philodendron hederaceum",
        watering = "Daily",
        recommendations = listOf("Use well-draining soil.", "Mist leaves occasionally.", "Fertilize monthly during growing season."),
        imageUrl = "https://source.unsplash.com/featured/?plant,17",
        streak = 13,
        lastWatered = "2025-05-04",
        idGarden = 5,
        difficulty = "Medium",
        shadeLevel = 2
    ),
    Plant(
        id = "19",
        name = "Chinese Evergreen",
        scientificName = "Aglaonema commutatum",
        watering = "Every 3 days",
        recommendations = listOf("Use well-draining soil.", "Keep away from pets.", "Fertilize monthly during growing season."),
        imageUrl = "https://source.unsplash.com/featured/?plant,18",
        streak = 7,
        lastWatered = "2025-05-14",
        idGarden = 1,
        difficulty = "Hard",
        shadeLevel = 5
    ),
    Plant(
        id = "20",
        name = "Boston Fern",
        scientificName = "Nephrolepis exaltata bostoniensis",
        watering = "Bi-weekly",
        recommendations = listOf("Fertilize monthly during growing season.", "Fertilize monthly during growing season.", "Keep away from pets."),
        imageUrl = "https://source.unsplash.com/featured/?plant,19",
        streak = 7,
        lastWatered = "2025-05-12",
        idGarden = 4,
        difficulty = "Easy",
        shadeLevel = 1
    ),
    Plant(
        id = "21",
        name = "English Ivy",
        scientificName = "Hedera helix",
        watering = "Daily",
        recommendations = listOf("Water regularly but avoid overwatering.", "Mist leaves occasionally.", "Water regularly but avoid overwatering."),
        imageUrl = "https://source.unsplash.com/featured/?plant,20",
        streak = 27,
        lastWatered = "2025-05-20",
        idGarden = 1,
        difficulty = "Easy",
        shadeLevel = 1
    ),
    Plant(
        id = "22",
        name = "Swiss Cheese Plant",
        scientificName = "Monstera adansonii",
        watering = "Bi-weekly",
        recommendations = listOf("Use well-draining soil.", "Water regularly but avoid overwatering.", "Use well-draining soil."),
        imageUrl = "https://source.unsplash.com/featured/?plant,21",
        streak = 15,
        lastWatered = "2025-05-11",
        idGarden = 5,
        difficulty = "Medium",
        shadeLevel = 2
    ),
    Plant(
        id = "23",
        name = "Cast Iron Plant",
        scientificName = "Aspidistra elatior",
        watering = "Weekly",
        recommendations = listOf("Fertilize monthly during growing season.", "Fertilize monthly during growing season.", "Mist leaves occasionally."),
        imageUrl = "https://source.unsplash.com/featured/?plant,22",
        streak = 22,
        lastWatered = "2025-05-08",
        idGarden = 5,
        difficulty = "Hard",
        shadeLevel = 3
    ),
    Plant(
        id = "24",
        name = "Prayer Plant",
        scientificName = "Maranta leuconeura",
        watering = "Weekly",
        recommendations = listOf("Fertilize monthly during growing season.", "Mist leaves occasionally.", "Water regularly but avoid overwatering."),
        imageUrl = "https://source.unsplash.com/featured/?plant,23",
        streak = 25,
        lastWatered = "2025-05-07",
        idGarden = 1,
        difficulty = "Medium",
        shadeLevel = 4
    ),
    Plant(
        id = "25",
        name = "Oxalis",
        scientificName = "Oxalis triangularis",
        watering = "Daily",
        recommendations = listOf("Keep away from pets.", "Keep in indirect sunlight.", "Keep away from pets."),
        imageUrl = "https://source.unsplash.com/featured/?plant,24",
        streak = 6,
        lastWatered = "2025-05-09",
        idGarden = 4,
        difficulty = "Easy",
        shadeLevel = 4
    ),
    Plant(
        id = "26",
        name = "Purple Heart",
        scientificName = "Tradescantia pallida",
        watering = "Weekly",
        recommendations = listOf("Keep in indirect sunlight.", "Fertilize monthly during growing season.", "Fertilize monthly during growing season."),
        imageUrl = "https://source.unsplash.com/featured/?plant,25",
        streak = 26,
        lastWatered = "2025-05-03",
        idGarden = 4,
        difficulty = "Easy",
        shadeLevel = 1
    ),
    Plant(
        id = "27",
        name = "String of Pearls",
        scientificName = "Senecio rowleyanus",
        watering = "Every 3 days",
        recommendations = listOf("Mist leaves occasionally.", "Fertilize monthly during growing season.", "Use well-draining soil."),
        imageUrl = "https://source.unsplash.com/featured/?plant,26",
        streak = 4,
        lastWatered = "2025-05-09",
        idGarden = 1,
        difficulty = "Hard",
        shadeLevel = 1
    ),
    Plant(
        id = "28",
        name = "Kalanchoe",
        scientificName = "Kalanchoe blossfeldiana",
        watering = "Weekly",
        recommendations = listOf("Keep away from pets.", "Water regularly but avoid overwatering.", "Fertilize monthly during growing season."),
        imageUrl = "https://source.unsplash.com/featured/?plant,27",
        streak = 11,
        lastWatered = "2025-05-11",
        idGarden = 4,
        difficulty = "Hard",
        shadeLevel = 5
    ),
    Plant(
        id = "29",
        name = "Begonia",
        scientificName = "Begonia rex",
        watering = "Daily",
        recommendations = listOf("Keep in indirect sunlight.", "Keep away from pets.", "Fertilize monthly during growing season."),
        imageUrl = "https://source.unsplash.com/featured/?plant,28",
        streak = 2,
        lastWatered = "2025-05-20",
        idGarden = 5,
        difficulty = "Medium",
        shadeLevel = 3
    ),
    Plant(
        id = "30",
        name = "Coleus",
        scientificName = "Solenostemon scutellarioides",
        watering = "Weekly",
        recommendations = listOf("Fertilize monthly during growing season.", "Fertilize monthly during growing season.", "Use well-draining soil."),
        imageUrl = "https://source.unsplash.com/featured/?plant,29",
        streak = 12,
        lastWatered = "2025-05-12",
        idGarden = 5,
        difficulty = "Easy",
        shadeLevel = 2
    )
)