package com.example.viridis.dummyData

import com.example.viridis.data.model.Plant

val dummyPlants = listOf(
    Plant(
        id = "1",
        name = "Aloe Vera",
        scientificName = "Aloe barbadensis",
        watering = "Bi-weekly",
        recommendations = listOf("Keep in indirect sunlight.", "Water regularly but avoid overwatering.", "Use well-draining soil."),
        imageUrl = "https://es.wikipedia.org/wiki/Aloe_vera#/media/Archivo:Flore_m%C3%A9dicale_des_Antilles,_ou,_Trait%C3%A9_des_plantes_usuelles_(Pl._130)_(8203076070).jpg",
        streak = 3,
        lastWatered = "2025-05-08",
        idGarden = 1,
        difficulty = "Medium",
        shadeLevel = "part_shade"
    ),
    Plant(
        id = "2",
        name = "Snake Plant",
        scientificName = "Sansevieria trifasciata",
        watering = "Bi-weekly",
        recommendations = listOf("Keep in indirect sunlight.", "Water regularly but avoid overwatering.", "Fertilize monthly during growing season."),
        imageUrl = "https://source.unsplash.com/featured/?plant,1",
        streak = 16,
        lastWatered = "2025-05-24",
        idGarden = 1,
        difficulty = "Hard",
        shadeLevel = "full_sun"
    ),
    Plant(
        id = "3",
        name = "Peace Lily",
        scientificName = "Spathiphyllum wallisii",
        watering = "Daily",
        recommendations = listOf("Mist leaves occasionally.", "Keep in indirect sunlight.", "Use well-draining soil."),
        imageUrl = "https://source.unsplash.com/featured/?plant,2",
        streak = 15,
        lastWatered = "2025-05-02",
        idGarden = 1,
        difficulty = "Medium",
        shadeLevel = "sun-part_shade"
    ),
    Plant(
        id = "4",
        name = "Spider Plant",
        scientificName = "Chlorophytum comosum",
        watering = "Weekly",
        recommendations = listOf("Keep away from pets.", "Mist leaves occasionally.", "Use well-draining soil."),
        imageUrl = "https://source.unsplash.com/featured/?plant,3",
        streak = 15,
        lastWatered = "2025-05-06",
        idGarden = 2,
        difficulty = "Medium",
        shadeLevel = "part_shade"
    ),
    Plant(
        id = "5",
        name = "Pothos",
        scientificName = "Epipremnum aureum",
        watering = "Daily",
        recommendations = listOf("Mist leaves occasionally.", "Fertilize monthly during growing season.", "Keep in indirect sunlight."),
        imageUrl = "https://source.unsplash.com/featured/?plant,4",
        streak = 11,
        lastWatered = "2025-05-22",
        idGarden = 2,
        difficulty = "Hard",
        shadeLevel = "full_sun"
    ),
    Plant(
        id = "6",
        name = "ZZ Plant",
        scientificName = "Zamioculcas zamiifolia",
        watering = "Every 3 days",
        recommendations = listOf("Keep away from pets.", "Use well-draining soil.", "Mist leaves occasionally."),
        imageUrl = "https://source.unsplash.com/featured/?plant,5",
        streak = 16,
        lastWatered = "2025-05-11",
        idGarden = 2,
        difficulty = "Hard",
        shadeLevel = "full_shade"
    ),
    Plant(
        id = "7",
        name = "Fiddle Leaf Fig",
        scientificName = "Ficus lyrata",
        watering = "Every 3 days",
        recommendations = listOf("Keep in indirect sunlight.", "Mist leaves occasionally.", "Keep away from pets."),
        imageUrl = "https://source.unsplash.com/featured/?plant,6",
        streak = 8,
        lastWatered = "2025-05-22",
        idGarden = 3,
        difficulty = "Easy",
        shadeLevel = "part_shade"
    ),
    Plant(
        id = "8",
        name = "Rubber Plant",
        scientificName = "Ficus elastica",
        watering = "Bi-weekly",
        recommendations = listOf("Keep away from pets.", "Keep away from pets.", "Use well-draining soil."),
        imageUrl = "https://source.unsplash.com/featured/?plant,7",
        streak = 2,
        lastWatered = "2025-05-16",
        idGarden = 3,
        difficulty = "Hard",
        shadeLevel = "full_shade"
    ),
    Plant(
        id = "9",
        name = "Areca Palm",
        scientificName = "Dypsis lutescens",
        watering = "Weekly",
        recommendations = listOf("Fertilize monthly during growing season.", "Water regularly but avoid overwatering.", "Mist leaves occasionally."),
        imageUrl = "https://source.unsplash.com/featured/?plant,8",
        streak = 5,
        lastWatered = "2025-05-17",
        idGarden = 3,
        difficulty = "Easy",
        shadeLevel = "sun-part_shade"
    ),
    Plant(
        id = "10",
        name = "Jade Plant",
        scientificName = "Crassula ovata",
        watering = "Bi-weekly",
        recommendations = listOf("Fertilize monthly during growing season.", "Fertilize monthly during growing season.", "Mist leaves occasionally."),
        imageUrl = "https://source.unsplash.com/featured/?plant,9",
        streak = 14,
        lastWatered = "2025-05-13",
        idGarden = 4,
        difficulty = "Easy",
        shadeLevel = "part_shade"
    ),
    Plant(
        id = "11",
        name = "Fern",
        scientificName = "Nephrolepis exaltata",
        watering = "Every 3 days",
        recommendations = listOf("Mist leaves occasionally.", "Water regularly but avoid overwatering.", "Keep in indirect sunlight."),
        imageUrl = "https://source.unsplash.com/featured/?plant,10",
        streak = 13,
        lastWatered = "2025-05-21",
        idGarden = 4,
        difficulty = "Easy",
        shadeLevel = "full_shade"
    ),
    Plant(
        id = "12",
        name = "Croton",
        scientificName = "Codiaeum variegatum",
        watering = "Weekly",
        recommendations = listOf("Keep in indirect sunlight.", "Mist leaves occasionally.", "Keep away from pets."),
        imageUrl = "https://source.unsplash.com/featured/?plant,11",
        streak = 3,
        lastWatered = "2025-05-10",
        idGarden = 4,
        difficulty = "Medium",
        shadeLevel = "full_shade"
    )
)