package com.example.viridis.dummyData

import com.example.viridis.data.model.Plant

val dummyPlants = listOf(
    Plant(
        id = "1",
        name = "Aloe Vera",
        scientificName = "Aloe barbadensis",
        watering = "Bi-weekly",
        recommendations = listOf("Keep in indirect sunlight.", "Water regularly but avoid overwatering.", "Use well-draining soil."),
        imageUrl = "https://media.post.rvohealth.io/wp-content/uploads/sites/3/2025/04/aloe-vera-GettyImages-1473547826-Thumb.jpg",
        streak = 3,
        lastWatered = "2025-05-08",
        idGarden = 1,
        difficulty = "Medium",
        shadeLevel = "part_shade"
    ),
    Plant(
        id = "2",
        name = "Snake Plant",
        scientificName = "Sansevieria trifasciata",
        watering = "Bi-weekly",
        recommendations = listOf("Keep in indirect sunlight.", "Water regularly but avoid overwatering.", "Fertilize monthly during growing season."),
        imageUrl = "https://gardeningsg.nparks.gov.sg/images/Plants/snake_plant(4)_zara_chin.jpg",
        streak = 16,
        lastWatered = "2025-05-24",
        idGarden = 1,
        difficulty = "Hard",
        shadeLevel = "full_sun"
    ),
    Plant(
        id = "3",
        name = "Peace Lily",
        scientificName = "Spathiphyllum wallisii",
        watering = "Daily",
        recommendations = listOf("Mist leaves occasionally.", "Keep in indirect sunlight.", "Use well-draining soil."),
        imageUrl = "https://cdn.mos.cms.futurecdn.net/qYNPupRnspGWPF4886Z7hB-1200-80.jpg",
        streak = 15,
        lastWatered = "2025-05-02",
        idGarden = 1,
        difficulty = "Medium",
        shadeLevel = "sun-part_shade"
    ),
    Plant(
        id = "4",
        name = "Spider Plant",
        scientificName = "Chlorophytum comosum",
        watering = "Weekly",
        recommendations = listOf("Keep away from pets.", "Mist leaves occasionally.", "Use well-draining soil."),
        imageUrl = "https://cityfloralgreenhouse.com/wp-content/uploads/2020/09/spider-plant.jpg",
        streak = 15,
        lastWatered = "2025-05-06",
        idGarden = 2,
        difficulty = "Medium",
        shadeLevel = "part_shade"
    ),
    Plant(
        id = "5",
        name = "Pothos",
        scientificName = "Epipremnum aureum",
        watering = "Daily",
        recommendations = listOf("Mist leaves occasionally.", "Fertilize monthly during growing season.", "Keep in indirect sunlight."),
        imageUrl = "https://www.marthastewart.com/thmb/9etIquryA7k90xAxOOOwAVZMA60=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-2170686151-675aeaba15364e1c876dc485f7e6d8d8.jpg",
        streak = 11,
        lastWatered = "2025-05-22",
        idGarden = 2,
        difficulty = "Hard",
        shadeLevel = "full_sun"
    ),
    Plant(
        id = "6",
        name = "ZZ Plant",
        scientificName = "Zamioculcas zamiifolia",
        watering = "Every 3 days",
        recommendations = listOf("Keep away from pets.", "Use well-draining soil.", "Mist leaves occasionally."),
        imageUrl = "https://www.realsimple.com/thmb/9yMs2mrJjeQ_UsNZajI85Z5VI9w=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/zz-plant-GettyImages-1387302222-e9e228907c3e4e4ea3481898c90d1a53.jpg",
        streak = 16,
        lastWatered = "2025-05-11",
        idGarden = 2,
        difficulty = "Hard",
        shadeLevel = "full_shade"
    ),
    Plant(
        id = "7",
        name = "Fiddle Leaf Fig",
        scientificName = "Ficus lyrata",
        watering = "Every 3 days",
        recommendations = listOf("Keep in indirect sunlight.", "Mist leaves occasionally.", "Keep away from pets."),
        imageUrl = "https://plantandpot.nz/wp-content/uploads/2022/03/Tall-Fiddle-Leaf-Figs-30cm-scaled.jpg",
        streak = 8,
        lastWatered = "2025-05-22",
        idGarden = 3,
        difficulty = "Easy",
        shadeLevel = "part_shade"
    ),
    Plant(
        id = "8",
        name = "Rubber Plant",
        scientificName = "Ficus elastica",
        watering = "Bi-weekly",
        recommendations = listOf("Keep away from pets.", "Keep away from pets.", "Use well-draining soil."),
        imageUrl = "https://shop-static.arborday.org/media/0004362_tineke-variegated-rubber-tree.jpeg",
        streak = 2,
        lastWatered = "2025-05-16",
        idGarden = 3,
        difficulty = "Hard",
        shadeLevel = "full_shade"
    ),
    Plant(
        id = "9",
        name = "Areca Palm",
        scientificName = "Dypsis lutescens",
        watering = "Weekly",
        recommendations = listOf("Fertilize monthly during growing season.", "Water regularly but avoid overwatering.", "Mist leaves occasionally."),
        imageUrl = "https://www.gardenia.net/wp-content/uploads/2024/01/shutterstock_2334747645-800x533.jpg",
        streak = 5,
        lastWatered = "2025-05-17",
        idGarden = 3,
        difficulty = "Easy",
        shadeLevel = "sun-part_shade"
    ),
    Plant(
        id = "10",
        name = "Jade Plant",
        scientificName = "Crassula ovata",
        watering = "Bi-weekly",
        recommendations = listOf("Fertilize monthly during growing season.", "Fertilize monthly during growing season.", "Mist leaves occasionally."),
        imageUrl = "https://www.marthastewart.com/thmb/wfMSnhZFCSX45OgGrC37o8YWFcI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/grow-care-for-jade-plant-outside-getty-1123-6f0b4051fcd14580886a5431bc05b176.jpg",
        streak = 14,
        lastWatered = "2025-05-13",
        idGarden = 4,
        difficulty = "Easy",
        shadeLevel = "part_shade"
    ),
    Plant(
        id = "11",
        name = "Fern",
        scientificName = "Nephrolepis exaltata",
        watering = "Every 3 days",
        recommendations = listOf("Mist leaves occasionally.", "Water regularly but avoid overwatering.", "Keep in indirect sunlight."),
        imageUrl = "https://www.southernliving.com/thmb/9xe_bUwg_gJ1leAk8UZxtpAO2IM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/gettyimages-1026378744-1-8e6bdd98366d4686b765313800f32f52.jpg",
        streak = 13,
        lastWatered = "2025-05-21",
        idGarden = 4,
        difficulty = "Easy",
        shadeLevel = "full_shade"
    ),
    Plant(
        id = "12",
        name = "Croton",
        scientificName = "Codiaeum variegatum",
        watering = "Weekly",
        recommendations = listOf("Keep in indirect sunlight.", "Mist leaves occasionally.", "Keep away from pets."),
        imageUrl = "https://www.hola.com/horizon/original_aspect_ratio/8156815d719a-cuidados-croton-03a-a.jpg",
        streak = 3,
        lastWatered = "2025-05-10",
        idGarden = 4,
        difficulty = "Medium",
        shadeLevel = "full_shade"
    )
)